apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashu-rtp
  namespace: ashishNameSpace
spec:
  replicas: 4
  selector:
    matchLabels:
      app:  ashu-rtp
  template:
    metadata:
      labels:
        app:  ashu-rtp
    spec:
      imagePullSecrets:
      - name: cred
      containers:
      - name:  ashu-rtp
        image: stalin.jfrog.io/default-docker-local/ashu-rtp:2.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: CONSUMER_KEY
          value: "HpwdfLFZLON0mT8BLWSSYfTxs"
        - name: CONSUMER_SECRET
          value: "0FKwKj0GuPMz50dYTYQ3EQxqHfSyNsxipyfPGgXemMHkfWuR3G"
        - name: ACCESS_TOKEN
          value: "19703354-imHt92QNIdQLkRiV5qQXQw5CLoJmZM5stZkJ05796"
        - name: ACCESS_TOKEN_SECRET
          value: "G1yk87c6rXTd6B4kcKzJlfdsQyKlp0n8YYamya6D2M1eY"
