apiVersion: v1
kind: Service
metadata:
  name:  ashu-rtp-service
  namespace: ashishnamenpace
spec:
  type: NodePort
  selector:
    app: ashu-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
